### ISSUE TITLE
font size setting

### ISSUE THREAD

**Issue by pesegolsson** [SoRadGaming/Simple-HUD-Enhanced#10]
could we possibly get a font size option in the settings?

**Comment by SoRadGaming** [comment]
I will see what can be done, but Mojang hard codded the font height value to `fontHeight = 9`, and only adjusted the scale with a multiply function. So the only way to make text larger is to increase the Hud scale. (Overriding this function will override it everywhere it is used). I will try to find a solution, but will take a while.

**Comment by SoRadGaming** [comment]
Update: I Got Text Scaling working (reliable method), so I need to improve implementation. I'm going to be busy for a week, so I will start testing and getting it working next week.
