### ISSUE TITLE
missing parentheses

### ISSUE THREAD

**Issue by pesegolsson** [SoRadGaming/Simple-HUD-Enhanced#2]
Hi!
there is a missing parentheses in the direction part of the hud text. it shows (East with no trailing parentheses.

not a big thing but i'm sure it will annoy many when they notice it.

**Comment by SoRadGaming** [comment]
Yeah, a bit of an oversight.
I will fix it in the next update, along with the player ping option being added.

**Comment by SoRadGaming** [comment]
Fixed in 1.1.0 - (Files Generating Now)
