### ISSUE TITLE
Showing 0 when armour is not equiped.

### ISSUE THREAD

**Issue by WobbyChip** [SoRadGaming/Simple-HUD-Enhanced#27]
**Describe the bug**
Slots where armor is supposed to be shown show 0 when not equipped.

**To Reproduce**
1. Open the game

**Expected behavior**
I think that those 0 should not be there.

**Screenshots**
![image](https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/66483092/bf5ee89a-2199-4824-b90e-42a4eb6544d9)

**Minecraft (please complete the following information):**
 - Game Version 1.20.2
 - Mod Version 4.3.0

**Comment by SoRadGaming** [comment]
Do you have anything equipped or any other mods that have custom armour? As my code should, by default, have no text, 0 can only be added when getting the durability of the item or getting the amount of the item (which armour doesn't support). Also, it's weird that there are 5 of the "0".

**Comment by WobbyChip** [comment]
> Do you have anything equipped or any other mods that have custom armour? As my code should, by default, have no text, 0 can only be added when getting the durability of the item or getting the amount of the item (which armour doesn't support). Also, it's weird that there are 5 of the "0".

These are the mods that I have and yes, I can confirm it was a conflict with mod Visible Barriers: https://modrinth.com/mod/visiblebarriers
![image](https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/66483092/bd261576-575a-497c-bfb1-785817e910f2)

**Comment by SoRadGaming** [comment]
Thanks for the information, I will try to get this fixed with Update 4.4.0 https://github.com/SoRadGaming/Simple-HUD-Enhanced/pull/26

**Comment by SoRadGaming** [comment]
I found the issue: their mod makes air blocks visible, and my mod treats air as nothing; hence, they override the code and make it appear anyway. I fixed it now (I just checked for item count); I'm just trying to get other features in the update working before release.
