### ISSUE TITLE
[Request][Mod Support] Auto Hide upon Cobblemon Battle

### ISSUE THREAD

**Issue by KhaozFrost** [SoRadGaming/Simple-HUD-Enhanced#30]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/15788954/d095b073-6e67-4e1b-8438-62d64716f1c2)
https://modrinth.com/mod/cobblemon
**Describe the solution you'd like**
I would like to have the whole hud disable itself so that it doesnt overlap whenever a player goes into battle with a pokemon.
I love this hud mod more then any that i've seen but they're all plagued with this one issue. I know its possible to move elements around but i think it would be way cleaner to just auto hide whilst in battle and bring it back when battle is over.

**Comment by SoRadGaming** [comment]
I'll look into it. Thank you for the feature request.

**Comment by SoRadGaming** [comment]
Unfortunately, this is not possible, as Cobblemon does not have a developer API; I would recommend using the quick toggle shortcut to disable and enable the hud, "~" by default, or change it to a more accessible button in the Hotkeys Settings Page of Minecraft.

**Comment by KhaozFrost** [comment]
> Unfortunately, this is not possible, as Cobblemon does not have a developer API; I would recommend using the quick toggle shortcut to disable and enable the hud, "~" by default, or change it to a more accessible button in the Hotkeys Settings Page of Minecraft.

![image](https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/15788954/d9e43f26-4f96-496c-89a1-848658f2e585)

**Comment by SoRadGaming** [comment]
? That is not a Dev API, and even if it was, there are no events or documentation about it. If you figure it out feel free to open a PR.
