### ISSUE TITLE
[Crash] Crash with supplementaries

### ISSUE THREAD

**Issue by lostopkk** [SoRadGaming/Simple-HUD-Enhanced#33]
https://mclo.gs/SfwUCTk

**Comment by SoRadGaming** [comment]
Would you mind testing this fix for it, and let me know of any issues related to this fix, as there are two potential solutions? Also, did this issue happen before v4.6.0? Thank you.

[simple-hud-enhanced+1.20-1.20.4-4.6.1.zip](https://github.com/SoRadGaming/Simple-HUD-Enhanced/files/13642613/simple-hud-enhanced%2B1.20-1.20.4-4.6.1.zip)

**Comment by lostopkk** [comment]
> Would you mind testing this fix for it, and let me know of any issues related to this fix, as there are two potential solutions. Also, did this issue happen before v4.6.0? Thank you.
> 
> [simple-hud-enhanced+1.20-1.20.4-4.6.1.zip](https://github.com/SoRadGaming/Simple-HUD-Enhanced/files/13642661/simple-hud-enhanced%2B1.20-1.20.4-4.6.1.zip)

solved! thank you :)
