### ISSUE TITLE
Armor %

### ISSUE THREAD

**Issue by jurohn** [SoRadGaming/Simple-HUD-Enhanced#40]
**Is your feature request related to a problem? Please describe.**
No its not

**Describe the solution you'd like**
I would like to have the option to change (for example) 407 health remaining on a helmet, 100% left of an helmet.

**Describe alternatives you've considered**
400/407 left, so i can see how many it should have. Or at least an option for me to select to display it this way.

**Additional context**
My first request of choosing % left would be best for me. The option should be toggled on or off.

**Comment by jurohn** [comment]
Close this please. I didnt see this was already available. Thank you for your hard work on this plugin!

**Comment by SoRadGaming** [comment]
I appreciate the kind words 😊
