### ISSUE TITLE
Day Counter

### ISSUE THREAD

**Issue by Fyoncle** [SoRadGaming/Simple-HUD-Enhanced#42]
**Is your feature request related to a problem? Please describe.**
I'm always curious about what day my survival world is in, so a day counter would be perfect!

**Describe the solution you'd like**
A Day Counter in the config!

**Describe alternatives you've considered**
https://modrinth.com/mod/gui-clock/versions I used that but its not really the best solution since its not looks perfect with other mods like FPS counter, your mod is multi-functioning so it would be perfect on the listing if you add a day counter.

**Additional context**
![image](https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/63975256/b21d0c87-f1cf-47f3-87b4-87a7eabec737)

**Comment by SoRadGaming** [comment]
I'm happy to add this to the mod; I am super busy this week, but I will properly start working on it on the 25th when I'm free.
