### ISSUE TITLE
Sub-Chunk Coordinates

### ISSUE THREAD

**Issue by Stonehawk** [SoRadGaming/Simple-HUD-Enhanced#44]
Each individual chunk in minecraft is subdivided, as you know, into 16x16x16 blocks. If one wishes to minimize redstone errors, or (on a server where land is claimed in whole chunks) optimize land usage, knowing where one is within a given chunk is very helpful.

Displaying sub-chunk coordinates (positive integers 1-16 on x, y, and z values) will allow a player to see, at a glance, if they are right in the middle of a chunk horizontally but at its bottom (8X 8Y 1Z) or if they are standing at the corner of the chunk near-but-not-quite-at the upper limit of its top face (1X 1Y 12Z)

I have used other hud mods which display this information, and would like to switch to this more versatile solution if it adopts this feature. This information is also available readily on the F3 screen, but due to the cluttering nature of the F3 screen, it would be preferable to not have to play with it open.

I did search for any instances of the text "sub-chunk" or "subchunk" in the code which leads me to believe it is not yet supported.
if it is supported already, however, then I thank you and withdraw my request.

**Comment by SoRadGaming** [comment]
Thank you for the well-written issue; I'm happy to add this. I was working on a new configuration screen for this mod, where you can drag and drop/snap the hud wherever, but it's taking a while to develop (updates on my Discord). Might skip it for now and just add this feature and fix other issues listed in the git. 

Will add this feature same time as the day counting request.
