### ISSUE TITLE
Background does not move if text alignment moves

### ISSUE THREAD

**Issue by fallenistaken** [SoRadGaming/Simple-HUD-Enhanced#54]
**Describe the bug**
If the background is enabled and text alignment is set to right, the background alignment does not change.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the text alignment to right or center.

**Expected behaviour**
The background also updating the alignment,

**Screenshots**
![javaw_Avb9WuWxGF](https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/143284992/bc39b4b2-d496-4fa7-8934-71fbc1888b86)

**Minecraft Versions:**
 - Game Version [1.21]
 - Mod Version [v4.6.2]

**Comment by SoRadGaming** [comment]
Thank you for the image and the well-written bug report; thanks for bringing the issue to my attention; I have found the issue in the code and will push the update along with Update 4.7.0.

![2024-06-16_01 14 51](https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/47128515/d4dbb65f-c4ed-4a1d-92ea-c296a14baba7)
