### ISSUE TITLE
Compliance with Status Effect Bars' license

### ISSUE THREAD

**Issue by A5b84** [SoRadGaming/Simple-HUD-Enhanced#56]
Hi! I've noticed your mod includes parts of Status Effect Bars as mentioned in your readme, but I think your mod may not comply with some points of the LGPL license (nothing scary, just some simple fixes to make):

- As per the LGPL license, code from my mod must be licensed under LGPL in your mod as well. Currently your mod is licensed under MIT and (unless I'm mistaken) doesn't mention which parts are licensed under LGPL, so I'd recommend adding a notice like the following at the top of every file based on LGPL sources (StatusEffectInstanceMixin, StatusEffectInstanceDuck, StatusEffectBarRenderer, and any other I might have missed):
```
Copyright (C) 2024  A5b84, SoRadGaming

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```
(or a shorter version like this)
```
Copyright (C) 2024  A5b84, SoRadGaming

This program is licensed under the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
```
(Alternatively you can make a list of files licensed under LGPL and put it somewhere "prominent")

- You included the COPYING file in your project but you're missing the [COPYING.LESSER](https://github.com/A5b84/status-effect-bars/blob/main/COPYING.LESSER) file (strictly speaking this is allowed by the license but it has implications that may not be intentional so I'd recommend adding the second file)

Thanks :)

**Comment by SoRadGaming** [comment]
Thank you for the comprehensive heads-up. My [PR](https://github.com/SoRadGaming/Simple-HUD-Enhanced/pull/46) will remove all LGPL codes, but I will still provide the copying and continue to include you as a contributor to the mod.
