### ISSUE TITLE
Add Chinese support.

### ISSUE THREAD

**Issue by FyrGlow** [SoRadGaming/Simple-HUD-Enhanced#57]
# Request to add Chinese language support.
zh_cn.json File:
[zh_cn.json](https://github.com/user-attachments/files/15943988/zh_cn.json)

**Comment by fuyuan233** [comment]
在作者更新前，我建议先提交至
[自动汉化更新](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package)
[提交教程](https://www.bilibili.com/video/BV1Xi4y1r7S2)

**Comment by SoRadGaming** [comment]
Thank you for the language file. It will be added to the next mod update!
