### ISSUE TITLE
Armor HUD does not update on settings change

### ISSUE THREAD

**Issue by JacksonChen666** [SoRadGaming/Simple-HUD-Enhanced#58]
**Describe the bug**
Changing settings like "Display Total Durability" will not be immediately reflected in the HUD (unless updated via other means like durability change, armor equipping or unequipping, or item change).

**To Reproduce**
Steps to reproduce the behaviour:
1. Wear some piece of armor
2. Open settings for the mod
3. Go to "Equipment Status"
4. Change any setting under the "Equipment Elements" section
5. Save settings and go back to game
6. Observe that the settings haven't been applied
7. (workaround to make settings apply) Switch to another item, equip or unequip a piece of armor, or use the durability or armor, or something that updates the HUD. 

**Expected behaviour**

**Screenshots**

**Minecraft (please complete the following information):**
 - Game Version 1.20.4
 - Mod Version: 4.7.0

**Additional context**

**Comment by SoRadGaming** [comment]
Oh yep, I recreated the same issue on all game versions; I forgot to invalidate the cache on config updates; it's a simple fix; thanks for bringing it to my attention.
