### ISSUE TITLE
Add C, E, and P (rendered chunks, entities, and particles) Counters

### ISSUE THREAD

**Issue by KingCamren** [SoRadGaming/Simple-HUD-Enhanced#59]
**Is your feature request related to a problem? Please describe.**
Since jumping from 1.8.9 to more modern versions, I've been frustrated by how few mods offer specifically C and E counters as something they display in the overlay HUD (that is, intended to be always visible, unlike HUDs like the F3/debug menu that are meant to be toggled as needed), and how even fewer of these mods aren't overtly deep to the point of accidentally breaching some server's competitive rules.

**Describe the solution you'd like**
Similar to how they appear in the F3/debug menu, I am requesting the following counters be added as options to Simple HUD Enhanced:
- C counter (rendered chunks, often compared to the total chunk count in the loaded area, in the format `[rendered]/[total]`)
- E counter (rendered entities, often compared to the total loaded entities count, in the format `[rendered]/[total]`)
- P counter (loaded particles)
To the E counter request's extent, I am also tentatively suggesting adding the various loaded entities counters, as they are often an option whenever a mod offers the E counter:
- M counter (total monsters, aka hostile mobs, that count towards the mob cap)
- C counter (total creatures, aka passive mobs)
- etc.
This request, however, is **mainly made to request the C/rendered chunks and E/rendered entities counters**, as they're highly useful while caving/hunting for bastions.

**Describe alternatives you've considered**
I've tried some alternatives when pursuing mods that offer C and E counters in the overlay HUD, such as Minihud and BetterF3. However, Minihud is disallowed on some servers on account of having an entity health indicator module (which offers an unfair advantage in gamemodes like UHC), and BetterF3 is meant to replace the F3 screen entirely, so I either sacrifice my F3 menu's depth or opt for a cluttered screen.

**Additional context**
Two weeks ago, and one week after its most recent commit, you submitted a [pull request](https://github.com/johnvictorfs/simple-utilities-mod/pull/86) for a mod called "Simple HUD Utilities", citing how the mod had multiple unresolved issues and how your mod is more robust. I support the pull request's reasoning (especially on unresolved issues), but the mod's author stated they planned on adding C and E counters. To that extent, and because almost no mods offer them currently, I believe adding C and E counters are in your best interest.

**Comment by SoRadGaming** [comment]
Will look into adding it in Update 4.7.2

**Comment by SoRadGaming** [comment]
At this point, I will most likely only add a chunk counter and entity counter, maybe a monster and passive counter variant as well. Is that enough to close this feature request? Particles seem tough; I am looking into it now.

**Comment by KingCamren** [comment]
> At this point, I will most likely only add a chunk counter and entity counter, maybe a monster and passive counter variant as well. Is that enough to close this feature request? Particles seem tough; I am looking into it now.

That's close enough to the request to close it, yeah. Chunk and entity counters are by far the most useful for cave- and bastion-hunting. Other counters like particles are more performance-related, so they're probably better covered by debug-oriented mods like Minihud, whereas I've always seen Simple HUD Enhanced as more of a QoL mod for everyone to use.

Thanks for implementing the request!

**Comment by SoRadGaming** [comment]
Update: its all working,

Chunk Counter - Total / Loaded - Configurable
Entity Counter
Particle Counter

I am just working on other things, this update is ballooning into a new major release, but these features are already coded and working as of right now.

**Comment by KingCamren** [comment]
Great to hear! Looking forward to what else is coming in the major update as well, so here's hoping everything goes smoothly for you.

**Comment by SoRadGaming** [comment]
Just released a preview version of the mod, still testing and ensuring its stable, https://github.com/SoRadGaming/Simple-HUD-Enhanced/releases/tag/v4.7.2 let me know if you have any feedback, thx
