### ISSUE TITLE
no config menu

### ISSUE THREAD

**Issue by 7osanka** [SoRadGaming/Simple-HUD-Enhanced#6]
![image](https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/128554290/91db388a-87e6-4b75-8048-1f3c8ec11f80)

i reinstalled the mod and it still doesn't work

**Comment by SoRadGaming** [comment]
What mod version, and game version are you using? And also what are the other mods installed?

**Comment by SoRadGaming** [comment]
I Have not been able to recreate this issue on all versions, using the latest mod menu version for the given Minecraft version, if no response in  7 days ill consider the issue resolved
