### ISSUE TITLE
[Bug] Not updating on window resize

### ISSUE THREAD

**Issue by TQCnoARosto** [SoRadGaming/Simple-HUD-Enhanced#61]
**Describe the bug**
After a window resize the hud is not updating until hotbar is scrolled.

From standard resolution (800x600 or so) to fullscreen (F11). See the helmet position:
![image](https://github.com/user-attachments/assets/73e5fd14-6149-4f18-a980-8f08612d2074)
![image](https://github.com/user-attachments/assets/98630d36-fd0b-4351-bdd8-72e3b4183cdb)

**Minecraft**
 - Game Version: 1.21
 - Mod Version: 4.7.1

**Comment by SoRadGaming** [comment]
Is it just the equipment hud not updating? If so than I would know its a cache invalidation issue

**Comment by TQCnoARosto** [comment]
Yep hud only

**Comment by SoRadGaming** [comment]
Would you mind testing the new version, and let me know if the issue is resolved, thanks https://github.com/SoRadGaming/Simple-HUD-Enhanced/releases/tag/v4.7.2

**Comment by TQCnoARosto** [comment]
It works perfectly
