### ISSUE TITLE
Toolbar Scrolling HUD Update not working

### ISSUE THREAD

**Issue by SECO-Systeme** [SoRadGaming/Simple-HUD-Enhanced#62]
Describe the error
Changing weapons in the toolbar is not immediately reflected in the HUD (unless the change is made via using the weapon).

When scrolling in the toolbar, the weapons in the HUD are not automatically updated.
This still worked with the version simple-hud-enhanced+1.21-4.6.2.jar.

Screenshots
If necessary, add screenshots to explain your problem.

Minecraft (please fill out the following information):

Game version 1.21
Mod version: 4.7.1

**Comment by SoRadGaming** [comment]
Are you using the scroll wheel on the mouse? I remember there were issues with cache invalidation in certain conditions

**Comment by SECO-Systeme** [comment]
Yes I am using the scroll wheel.

**Comment by SoRadGaming** [comment]
Would you mind testing the new version, and let me know if the issue is resolved, thanks https://github.com/SoRadGaming/Simple-HUD-Enhanced/releases/tag/v4.7.2
