### ISSUE TITLE
Version 4.7.2 is not compatible with minecraft 1.21

### ISSUE THREAD

**Issue by kafeinnet** [SoRadGaming/Simple-HUD-Enhanced#64]
**Describe the bug**
The version file simple-hud-enhanced+1.21-1.21.1-4.7.2.jar is advertised as compatible 1.21 and 1.21.1 but it's not compatible with minecraft 1.21.

**To Reproduce**
Update the mod to the latest version but keep minecraft to version 1.21.

**Expected behaviour**
The mod is loaded with the game.

**Logs**
Here some logs with the error message and more information: https://mclo.gs/RVAutT9

**Minecraft (please complete the following information):**
 - Minecraft 1.21
 - Mod Version 4.7.2

**Comment by GanerCodes** [comment]
same issue here

**Comment by SoRadGaming** [comment]
oh no, it was a typo in the compatibility text, hotfixing now

**Comment by SoRadGaming** [comment]
in future pushing updates in the morning instead of before sleeping lol.

Pulled the Broken Versions from all Three Sources, and replaced with the hotfix version.
