### ISSUE TITLE
Even if you press the + and - icons in the settings window, nothing additional is displayed.

### ISSUE THREAD

**Issue by Mansick0070** [SoRadGaming/Simple-HUD-Enhanced#71]

**Comment by Mansick0070** [comment]
Pressing the + or - buttons in this window does not display any items.

![2024-12-08_06 43 01_2](https://github.com/user-attachments/assets/f3294d05-0d0c-4822-bad4-fe8d22a6b38a)

**Comment by SoRadGaming** [comment]
Thanks for the follow-up, found the problem, ClothConfig had breaking changes in 1.12.4, will release a fix soon

**Comment by SoRadGaming** [comment]
issue is fixed, will be released with next update, adding other features now aswell
