### ISSUE TITLE
HUD is not visible on the screen

### ISSUE THREAD

**Issue by bolmae** [SoRadGaming/Simple-HUD-Enhanced#72]
HUD is not displayed even though 'Show HUD' is enabled.
But when I press F1, HUD is displayed, like these screenshots.

![2024-12-08_11 05 11](https://github.com/user-attachments/assets/4052e507-4178-4ec1-af37-ecf36990a929)
![2024-12-08_11 05 06](https://github.com/user-attachments/assets/b7349dfc-c44d-42b5-b5d8-8dbd22d51198)

This happened after I updated the game and mod version 1.21.1 to 1.21.4
It worked normally in version 1.21.1

I don't know if this problem only happens to me.

I'm currently using the following mods
![image](https://github.com/user-attachments/assets/dc8766a9-7fb4-4cf8-b7e0-7a99ab3e3778)

please help me.

**Comment by SoRadGaming** [comment]
it seems Xaeros Minimap is breaking my mod, I'm having the same issue, looking to fix it

**Comment by bolmae** [comment]
Thanks for your help. I hope the bug can be fixed. Thank you for always providing great mod.
