### ISSUE TITLE
Scoreboard editor

### ISSUE THREAD

**Issue by Amirsunrise** [SoRadGaming/Simple-HUD-Enhanced#9]
Your Mod is Great But it doesn't have this feature
scoreboard editor with: 
resizing feature
red numbers remover
background remover
and more related to scoreboard

![IMG_20230719_112928](https://github.com/SoRadGaming/Simple-HUD-Enhanced/assets/110076470/ebafda0c-68f5-4915-9d23-3a40da11e201)

**Comment by SoRadGaming** [comment]
This Seems out of Scope for this project, but maybe in the future, right now this mod and many others exist https://modrinth.com/mod/ugly-scoreboard-fix

**Comment by SoRadGaming** [comment]
Nvm, their mods kinda annoying, ill see what I can do about coding similar features
